import gsap from "gsap";
import Head from "next/head";
import { useEffect, useRef } from "react";

export default function Home() {
  useEffect(() => {
    gsap.to(".box", { rotation: "+=360", repeat: -1 });
  });

  return (
    <div>
      <Head>
        <title>Adhyaay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid h-screen place-items-center">
        <div className="box w-20 h-20 bg-green-50 flex place-content-center shadow rounded">
          Hello
        </div>
      </main>
    </div>
  );
}
