import Head from "next/head";
import Footer from "../components/Footer";

import Header from "../components/Header";

import AboutSection from "../components/sections/AboutSection";
import EventsSection from "../components/sections/EventsSection";
import HeroSection from "../components/sections/HeroSection";
import SponsorsSection from "../components/sections/SponsorsSection";

export default function HomePage() {
  return (
    <div>
      <Head>
        <title>Adhyaay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="overflow-x-hidden">
        <HeroSection />
        <AboutSection />
        <EventsSection />
        <SponsorsSection />
      </main>

      <Footer />
    </div>
  );
}
